//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XMLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XMLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CWLib.Resources.XMLResources", typeof(XMLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CarBrands&gt;
        ///  &lt;Carmake BrandId=&quot;1&quot; Name=&quot;Audi&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;2&quot; Name=&quot;BMW&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;3&quot; Name=&quot;Acura&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;4&quot; Name=&quot;Subaru&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;5&quot; Name=&quot;Mitsubishi&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;7&quot; Name=&quot;AC Cars Ltd &quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;8&quot; Name=&quot;Alfa Romeo&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;9&quot; Name=&quot;Aston Martin&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;10&quot; Name=&quot;BYD&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;11&quot; Name=&quot;Bentley&quot; /&gt;
        ///  &lt;Carmake BrandId=&quot;12&quot; Name=&quot;Brill [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarBrands {
            get {
                return ResourceManager.GetString("CarBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CarClasses&gt;
        ///  &lt;Class ClassId=&quot;1&quot; ClassName=&quot;A-класс&quot; /&gt;
        ///  &lt;Class ClassId=&quot;2&quot; ClassName=&quot;B-класс&quot; /&gt;
        ///  &lt;Class ClassId=&quot;3&quot; ClassName=&quot;B-класс кроссоверы&quot; /&gt;
        ///  &lt;Class ClassId=&quot;4&quot; ClassName=&quot;C-класс&quot; /&gt;
        ///  &lt;Class ClassId=&quot;5&quot; ClassName=&quot;C-класс кроссоверы&quot; /&gt;
        ///  &lt;Class ClassId=&quot;6&quot; ClassName=&quot;D-класс&quot; /&gt;
        ///  &lt;Class ClassId=&quot;7&quot; ClassName=&quot;D-класс кроссоверы&quot; /&gt;
        ///  &lt;Class ClassId=&quot;8&quot; ClassName=&quot;E-класс&quot; /&gt;
        ///  &lt;Class ClassId=&quot;9&quot; ClassName=&quot;E-класс кроссоверы&quot; /&gt;
        ///  &lt;Class  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarClasses {
            get {
                return ResourceManager.GetString("CarClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CarModels&gt;
        ///  &lt;Model Id=&quot;1&quot; BrandId=&quot;1&quot; Name=&quot;A1 хэтчбек до 2014 года&quot; ClassId=&quot;1&quot; ClassName=&quot;A-класс&quot; Descr=&quot;Audi A1 впервые показан в 2008 году, как концепт-кар. В 2010 году автомобиль пошел на конвейер. Audi А1 базируется на платформе VAG, аналогичной с Polo и Skoda Fabia.&quot; Vol=&quot;8,85504096&quot; /&gt;
        ///  &lt;Model Id=&quot;3&quot; BrandId=&quot;1&quot; Name=&quot;A3 хэтчбек&quot; ClassId=&quot;4&quot; ClassName=&quot;C-класс&quot; Descr=&quot;Audi A3 — хэтчбэк малого семейного класса, производимый концерном Volkswagen с 1996 год [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarModels {
            get {
                return ResourceManager.GetString("CarModels", resourceCulture);
            }
        }
    }
}
