//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarwashManager.Resources.TextStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarwashManager.Resources.TextStrings.WinNames", typeof(WinNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить приход.
        /// </summary>
        internal static string AddMoneyWindowName {
            get {
                return ResourceManager.GetString("AddMoneyWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник автомобилей.
        /// </summary>
        internal static string CarDictWindowName {
            get {
                return ResourceManager.GetString("CarDictWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касса.
        /// </summary>
        internal static string CashboxWindowName {
            get {
                return ResourceManager.GetString("CashboxWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник клиентов.
        /// </summary>
        internal static string ClientsDictWindowName {
            get {
                return ResourceManager.GetString("ClientsDictWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        internal static string LaunchWindowName {
            get {
                return ResourceManager.GetString("LaunchWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        internal static string LoginWindowName {
            get {
                return ResourceManager.GetString("LoginWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carwash Manager.
        /// </summary>
        internal static string MainWindowName {
            get {
                return ResourceManager.GetString("MainWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый бокс.
        /// </summary>
        internal static string NewBoxWindowName {
            get {
                return ResourceManager.GetString("NewBoxWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый заказ (мойка).
        /// </summary>
        internal static string NewCarwashOrderWindowName {
            get {
                return ResourceManager.GetString("NewCarwashOrderWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая услуга автомойки.
        /// </summary>
        internal static string NewCarwashServiceWindowName {
            get {
                return ResourceManager.GetString("NewCarwashServiceWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая категория авто.
        /// </summary>
        internal static string NewCategoryWindowName {
            get {
                return ResourceManager.GetString("NewCategoryWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиль клиента.
        /// </summary>
        internal static string NewClientCarsWindowName {
            get {
                return ResourceManager.GetString("NewClientCarsWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая группа клиентов.
        /// </summary>
        internal static string NewClientGroupWindowName {
            get {
                return ResourceManager.GetString("NewClientGroupWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый клиент.
        /// </summary>
        internal static string NewClientWindowName {
            get {
                return ResourceManager.GetString("NewClientWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый заказ - клиент.
        /// </summary>
        internal static string NewOrderLicenceWindowName {
            get {
                return ResourceManager.GetString("NewOrderLicenceWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая категория услуг.
        /// </summary>
        internal static string NewServiceCategoryWindowName {
            get {
                return ResourceManager.GetString("NewServiceCategoryWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый работник.
        /// </summary>
        internal static string NewWorkerWindowName {
            get {
                return ResourceManager.GetString("NewWorkerWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог услуг.
        /// </summary>
        internal static string ServicesDictWindowName {
            get {
                return ResourceManager.GetString("ServicesDictWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование бокса.
        /// </summary>
        internal static string UpdateBoxWindowName {
            get {
                return ResourceManager.GetString("UpdateBoxWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование заказа.
        /// </summary>
        internal static string UpdateCarwashOrderWindowName {
            get {
                return ResourceManager.GetString("UpdateCarwashOrderWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование услуги.
        /// </summary>
        internal static string UpdateCarwashServiceWindowName {
            get {
                return ResourceManager.GetString("UpdateCarwashServiceWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование категории авто.
        /// </summary>
        internal static string UpdateCategoryWindowName {
            get {
                return ResourceManager.GetString("UpdateCategoryWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование информации о клиенте.
        /// </summary>
        internal static string UpdateClientWindowName {
            get {
                return ResourceManager.GetString("UpdateClientWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование информации о работнике.
        /// </summary>
        internal static string UpdateWorkerWindowName {
            get {
                return ResourceManager.GetString("UpdateWorkerWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить расход.
        /// </summary>
        internal static string WithdrawMoneyWindowName {
            get {
                return ResourceManager.GetString("WithdrawMoneyWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник работников.
        /// </summary>
        internal static string WorkersDictWindowName {
            get {
                return ResourceManager.GetString("WorkersDictWindowName", resourceCulture);
            }
        }
    }
}
